[build]
command = "npm install --legacy-peer-deps --no-fund --no-audit && node cloudflare-build.js && npm run build"
publish = "dist/cloudflare"
node_version = "18.17.1"

[build.environment]
NODE_VERSION = "18.17.1"
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 