[build]
command = "npm install --no-corepack --legacy-peer-deps --no-fund --no-audit && node cloudflare-minimal-build.js && npm run build --no-corepack"
publish = "dist/cloudflare"
node_version = "16.20.0"

[build.environment]
NODE_VERSION = "16.20.0"
SKIP_COREPACK = "true"
NPM_FLAGS = "--no-corepack --legacy-peer-deps --no-fund --no-audit"
DISABLE_COREPACK = "1" 